---
name: Docker

on:
  workflow_dispatch:
  # workflow_call:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2.9.1

      - name: Install additional kernel modules needed for OPI like VRF
        run: |
          sudo apt-get update
          sudo apt-get install linux-modules-extra-$(uname -r)

      - name: Load additional kernel modules needed for OPI like VRF
        run: sudo modprobe -v vrf

      - name: Start containers
        run: docker-compose up --build --force-recreate --detach opi-test

      - name: Run Tests
        run: |
          set -x
          name=$(docker-compose ps | grep opi-test | awk '{print $1}')
          rc=$(docker wait "${name}")
          if [ "${rc}" != "0" ]; then
              echo "opi-test failed:"
              docker logs "${name}"
              exit 1
          fi
      - name: Logs
        if: always()
        run: docker-compose logs

      - name: Stop containers
        if: always()
        run: docker-compose down --volumes --remove-orphans
