name: Check Brew Update

on:
  push:
    branches:
          - master
          - xmlsec-1_2_x
  pull_request:
    branches:
          - master
          - xmlsec-1_2_x
  workflow_dispatch:

jobs:
  check-osx:
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        include:
          - config_flags:
          - config_flags: --enable-size-t=no
          - config_flags: --enable-md5
    steps:
    - name: install dependencies
      run: |
          unset HOMEBREW_NO_INSTALL_FROM_API
          brew update
          brew install automake autoconf pkg-config libtool
          # brew install libxml2 libxslt
          brew install openssl nspr nss libgcrypt gnutls
