name: check-edge-versions
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh
    
jobs:
  win:
    strategy:
      matrix:
        os: [windows-2022, windows-2019, ubuntu20]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Rename MSEdgeUpdate
      run: |
          rename-item -Path "C:\Program Files (x86)\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe" -NewName dis_MicrosoftEdgeUpdate.exe
      
    - name: Find versions
      run: |
          $browsers = @{
            edge = @{
                Name="Microsoft Edge";
                File="msedge.exe"
            }
          }
          $browserName = $browsers.edge.Name
          $browserFile = $browsers.edge.File
          $registryKey = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\$browserFile"
          $browserVersion = (Get-Item (Get-ItemProperty $registryKey)."(Default)").VersionInfo.FileVersion
          $browserVersion
          
          start-sleep 60
          $browserVersion = (Get-Item (Get-ItemProperty $registryKey)."(Default)").VersionInfo.FileVersion
          $browserVersion
    
  ubnt:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Get Edge Version
      run: |
          microsoft-edge --version
      
          
