name: databricks
on:
  workflow_dispatch:
  # pull_request_target:
  #   types: labeled

defaults:
  run:
    shell: bash
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Run TCPdump in background
      if: runner.os == 'Linux'
      run: |
        echo "start_tcp_dump=true" >> "$GITHUB_ENV"
        sudo tcpdump -i eth0 -w dump.pcap &
        
    - name: Install databricks
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

    - name: Stop TCPdump
      if: (success() || failure()) && env.start_tcp_dump == 'true' && runner.os == 'Linux'
      run: sudo killall tcpdump

    - name: Upload dump file
      if: (success() || failure()) && env.start_tcp_dump == 'true' && runner.os == 'Linux'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.run_id }}-${{ github.run_attempt }}.pcap
        path: dump.pcap

    - name: Test databricks
      run: |
        databricks version
      
