name: databricks
on:
  workflow_dispatch:
  # pull_request_target:
  #   types: labeled

defaults:
  run:
    shell: bash
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: Install databricks
      run: |
        curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

    - name: Test databricks
      run: |
        databricks version
      
