name: install-moby-compose

on:
  workflow_dispatch:

jobs:
  moby-compose:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: List
      run: |
          apt list -a moby-compose

    - name: install moby
      run: |
          sudo apt-get update
          sudo apt-get install -y --allow-downgrades moby-compose=2.18.1+azure-ubuntu20.04u2
          systemctl is-active --quiet docker.service || systemctl start docker.service
          systemctl is-enabled --quiet docker.service || systemctl enable docker.service

          sleep 10
          docker info


    - name: docker images
      run: |
          docker compose version
          docker image list

    - name: compose smoke test
      run: |
          cd apache-php
          docker compose up -d
          docker ps
          curl localhost:80

          sleep 10
          docker compose down
