name: run-macos-matrix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-13-xlarge, macos-14]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: |
          clt_placeholder="/tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress"
          sudo touch $clt_placeholder
          
          /usr/sbin/softwareupdate -l
