name: run-ubunu-matrix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-20.04, ubuntu-20.04, ubuntu-20.04, ubuntu-20.04]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: actions/checkout
          ref: main
