name: run-ubuntu-matrix

on:
  workflow_dispatch:
    inputs:
      TYPE:
        description: 'TYPE'
        required: true
      IMAGE_NAME:
        description: 'Image name'
        required: false
  # schedule:
  #   - cron: '0/5 * * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
      fail-fast: false
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3
      #   with:
      #     repository: actions/checkout
      #     ref: main

      - name: check nuget conf
        run: |
          which nuget
          nuget config -set maxHttpRequestsPerSource=64
          ls -la ~/.config/NuGet
          cat ~/.config/NuGet/NuGet.Config
          
      - name: Adding markdown 1
        shell: pwsh
        run: |
          if ("${{ inputs.TYPE }}" -eq "qq") {
            $imageName = "${{ inputs.IMAGE_NAME }}"
          }
          "## Details" >> $env:GITHUB_STEP_SUMMARY
          "| Source | Image Name | VM Name | VM User | Resource Group |" >> $env:GITHUB_STEP_SUMMARY
          "| ------------ | ------------- | ------------- | ----------- | ------------------- |" >> $env:GITHUB_STEP_SUMMARY
          "| ee | $imageName | ee | ee | ee |" >> $env:GITHUB_STEP_SUMMARY
          "  " >> $env:GITHUB_STEP_SUMMARY

      - name: Adding markdown 2
        run: echo '### Hello world2! :rocket:<br /> from ${{ matrix.os }}' >> $GITHUB_STEP_SUMMARY
