name: run-windows-matrix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
      fail-fast: false
    steps:
      - name: Run pwsh
        run: |
          Get-Content "$env:USERPROFILE/.docker/config.json"
          docker
        shell: pwsh
      - name: append env
        shell: pwsh
        run: |
          $env:PATH
          echo "c:\temp" >> "$GITHUB_PATH"
          $env:PATH
      - name: show PATH
        shell: pwsh
        run: |
          $env:PATH
