name: simulator-boot-times
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    
jobs:
  test:
    name: simulator-boot-times
    runs-on: macos-14
    permissions:
      actions: read

    steps:
    - name: Collect Workflow Telemetry
      uses: catchpoint/workflow-telemetry-action@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'

    # - run: xcrun simctl list -j

    - run: |
        DEVICE_TYPE_ID="com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
        RUNTIME_ID="com.apple.CoreSimulator.SimRuntime.iOS-17-4"
        SIMULATOR_NAME="my-ios17.4-sim"
        
        xcrun simctl bootstatus $(xcrun simctl create $SIMULATOR_NAME $DEVICE_TYPE_ID $RUNTIME_ID) -b
