name: simulator-boot-times
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash
    
jobs:
  test:
    name: simulator-boot-times
    runs-on: ${{ matrix.runs-on }}
    permissions:
      actions: read
    strategy:
      fail-fast: false
      matrix:
        include:
        - xcode: "15.3"
          runs-on: "macos-14"
          sim-type: "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
          sim-runtime: "com.apple.CoreSimulator.SimRuntime.iOS-17-4"

        - xcode: "15.3"
          runs-on: "macos-14"
          sim-type: "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
          sim-runtime: "com.apple.CoreSimulator.SimRuntime.iOS-17-2"

        - xcode: "15.3"
          runs-on: "macos-14"
          sim-type: "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
          sim-runtime: "com.apple.CoreSimulator.SimRuntime.iOS-17-0"

        - xcode: "15.2"
          runs-on: "macos-14"
          sim-type: "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
          sim-runtime: "com.apple.CoreSimulator.SimRuntime.iOS-17-4"

        - xcode: "15.2"
          runs-on: "macos-14"
          sim-type: "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
          sim-runtime: "com.apple.CoreSimulator.SimRuntime.iOS-17-2"

        - xcode: "15.2"
          runs-on: "macos-14"
          sim-type: "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
          sim-runtime: "com.apple.CoreSimulator.SimRuntime.iOS-17-0"

        - xcode: "15.0.1"
          runs-on: "macos-14"
          sim-type: "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
          sim-runtime: "com.apple.CoreSimulator.SimRuntime.iOS-17-4"
          
        - xcode: "15.0.1"
          runs-on: "macos-14"
          sim-type: "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
          sim-runtime: "com.apple.CoreSimulator.SimRuntime.iOS-17-2"

        - xcode: "15.0.1"
          runs-on: "macos-14"
          sim-type: "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
          sim-runtime: "com.apple.CoreSimulator.SimRuntime.iOS-17-0"

        - xcode: "14.3.1"
          runs-on: "macos-14"
          sim-type: "com.apple.CoreSimulator.SimDeviceType.iPhone-SE-3rd-generation"
          sim-runtime: "com.apple.CoreSimulator.SimRuntime.iOS-16-4"

    steps:
    - name: Collect Workflow Telemetry
      uses: catchpoint/workflow-telemetry-action@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}

    # - run: xcrun simctl list -j

    - run: |
        DEVICE_TYPE_ID=${{ matrix.sim-type }}
        RUNTIME_ID=${{ matrix.sim-runtime }}
        SIMULATOR_NAME="my-ios-sim"
        
        xcrun simctl bootstatus $(xcrun simctl create $SIMULATOR_NAME $DEVICE_TYPE_ID $RUNTIME_ID) -b
