name: test-python-cmake

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10','3.11', '3.11.1', '3.12']
        os: ['macos-12']
        try: ['0', '1']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup venv
        run: python3 -m venv venv && venv/bin/pip install --upgrade pip
      
      - name: install pyarrow
        run: venv/bin/pip install pyarrow==10.0.1
