name: test-VStudio-VCTools

on: [workflow_dispatch]

jobs:
  test1:
    runs-on: windows-2022
    steps:
    - name: Execute
      run:
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64

        echo %vctoolsversion%

        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
      shell: cmd
      
  test-workaround1:
    runs-on: windows-2022
    steps:
    - name: Workaround 1
      run: |
        rm "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\Microsoft.VCToolsVersion.v143.default.props"
        rm "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\Microsoft.VCToolsVersion.v143.default.txt"
    - name: Execute
      run:
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64

        echo %vctoolsversion%

        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
      shell: cmd

  test-workaround2:
    runs-on: windows-2022
    steps:
    - name: Workaround 2
      shell: pwsh
      run: |
        Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $componentsToRemove= @(
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ARM.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ARM",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ARM64.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ARM64",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL.ARM.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL.ARM",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL.ARM64.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL.ARM64",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.ATL",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC.ARM.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC.ARM",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC.ARM64.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC.ARM64",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.MFC",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.x86.x64.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.37.17.7.x86.x64",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ARM",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ARM.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ARM64",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ARM64.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL.ARM",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL.ARM.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL.ARM64",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL.ARM64.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.ATL.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC.ARM",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC.ARM.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC.ARM64",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC.ARM64.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.MFC.Spectre",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.x86.x64",
            "Microsoft.VisualStudio.Component.VC.14.38.17.8.x86.x64.Spectre"
        )
        [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --remove " +  $_}
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
        # should be run twice
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
    - name: Execute
      run:
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64

        echo %vctoolsversion%

        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
      shell: cmd
