# This is a basic workflow to help you get started with Actions

name: test-ubuntu-mount

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "*/15 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        try: ['0', '1', '2', '3', '4', '5']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: test
        run: |
         df -h
         sudo ls -la /mnt
         sudo cat /etc/fstab
         mount
        shell: bash
