name: test-ubuntu-ruby-v2

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04', 'ubuntu-24.04']
        ruby: ['3.1', '3.2', '3.3']

    steps:
      # - run: chmod -R o-w /opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems
      #   if: always()
      
      - name: Checkout current PR
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: puppetlabs/puppet-agent
          
      - name: Install Ruby version ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          
      - name: Update rubygems and install gems
        run: |
          gem update --system --silent --no-document
          bundle install --jobs 4 --retry 3
          
      - run: bundle exec rake rubocop
