name: test-ubuntu-ruby

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-22.04', 'ubuntu-24.04']
        ruby: ['3.1', '3.2', '3.3']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: permissions check-1
        run: |
          ls -la /opt/hostedtoolcache/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0
          ls -la /opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0
        shell: bash
        if: always()

      - name: Install Ruby version ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
        if: always()

      # - run: chmod -R o-w /opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0/gems
      #   if: always()

      - name: permissions check-2
        run: |
          ls -la /opt/hostedtoolcache/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0
          ls -la /opt/hostedtoolcache/Ruby/3.2.5/x64/lib/ruby/gems/3.2.0
          ls -la /opt/hostedtoolcache/Ruby/3.3.4/x64/lib/ruby/gems/3.3.0
        shell: bash
        if: always()

      - name: Prepare Gemfile
        if: always()
        run: |
          cat <<EOF > Gemfile
          source 'https://rubygems.org'

          gem 'faraday'
          EOF
      
      - name: bundle install
        if: always()
        run: bundle install
