name: test-python-cmake

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11.1]
        os: ['macos-12']
        try: ['0', '1', '2']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup venv
        run: python3 -m venv venv && venv/bin/pip install --upgrade pip
      
      - name: install pyarrow
        run: venv/bin/pip install pyarrow==10.0.1
