name: test-sslpoke

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04', 'ubuntu-latest']

    steps:
      # - name: test
      #   run: |
      #     wget https://confluence.atlassian.com/kb/files/779355358/779355357/1/1441897666313/SSLPoke.class
      #     $JAVA_HOME/bin/java SSLPoke pipelinesghubeus12.actions.githubusercontent.com 443
      #   shell: bash
      - name: test
        run: |
          sudo apt-get update && sudo apt-get install -y git python3-pip python3-venv
          sudo rm -rf /var/lib/apt/lists/*
          sudo pip3 install --no-cache-dir --upgrade pip pyorbs

          cd ~
          git clone https://github.com/logikal-io/ansible-public-playbooks.git
          cd ansible-public-playbooks
          sudo orb --make ansible --no-cache
          echo "BECOME" | sudo orb ansible -c './run-roles -r hadoop'

          cd ~
          git clone https://github.com/logikal-io/mindlab.git
          cd mindlab
          git checkout update-dependencies
          sudo orb --make mindlab --no-cache
          sudo source ~/.bashrc.d/hadoop.bashrc

          wget https://confluence.atlassian.com/kb/files/779355358/779355357/1/1441897666313/SSLPoke.class
          java -Djavax.net.debug=ssl SSLPoke pipelinesghubeus12.actions.githubusercontent.com 443
          
          orb mindlab -c "pytest --live -k 'spark and gs:'"
          
        shell: bash
