name: View env vars
on:
  workflow_dispatch:
  # pull_request_target:
  #   types: labeled

defaults:
  run:
    shell: pwsh
    
jobs:
  build:
    strategy:
      matrix:
        os: [macos-11, macos-12, ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: Print env vars
      run: 
        Get-ChildItem env:\
      
    - name: Print actions trigger
      run: Get-Content $env:GITHUB_EVENT_PATH | ConvertFrom-Json

    - name: Dump GitHub context and PATH
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
        echo "========================"
        echo "$PATH"

    - name: Check /etc/environment
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        cat /etc/environment

    - run: echo | openssl s_client -showcerts -servername pipelinesghubeus12.actions.githubusercontent.com -connect pipelinesghubeus12.actions.githubusercontent.com:443 2>/dev/null | openssl x509 -inform pem -noout -text
      shell: bash

    - name: Test unique id
      run: $actionUniqueId = "${{ github.run_id }}${{ github.run_number }}${{ github.run_attempt }}"[-9..-1] -join ""; write-host $actionUniqueId

    # - name: ll
    #   shell: bash
    #   run: |
    #     ll
      
#     - name: Test versions
#       run: |
#           $imageVersionComponents = $env:ImageVersion.Split('.')
#           $imageMajorVersion = $imageVersionComponents[0]
#           $imageMinorVersion = $imageVersionComponents[1]
#           if ("$imageMajorVersion.$imageMinorVersion" -ne '20230619.1') {
#             throw "Current runner $imageMajorVersion.$imageMinorVersion image version doesn't match ${{ github.event.client_payload.imageVersion }}."
#           }else{
#             Write-Host "Versions match"
#           }
        
