name: View env vars
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
        
    - name: Print env vars
      run: Get-ChildItem env:\
      
    - name: Test versions
      run: |
          $imageVersionComponents = $env:ImageVersion.Split('.')
          $imageMajorVersion = $imageVersionComponents[0]
          $imageMinorVersion = $imageVersionComponents[1]
          if ("$imageMajorVersion.$imageMinorVersion" -ne '20230619.1') {
            throw "Current runner $imageMajorVersion.$imageMinorVersion image version doesn't match ${{ github.event.client_payload.imageVersion }}."
          }else{
            Write-Host "Versions match"
          }
