name: view-android-components
on:
  workflow_dispatch:
  # pull_request_target:
  #   types: labeled
    
jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out code from GitHub
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: list android componnets
      shell: bash
      run: |
        SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
        ${SDKMANAGER} --list_installed
